import { createFileRoute, Link } from "@tanstack/react-router";
import { motion } from "framer-motion";
import { ArrowRight, Check, Gauge, Layers3, LockKeyhole, MonitorSmartphone, ShieldCheck, Sparkles, WandSparkles, Zap } from "lucide-react";
import { Header } from "@/components/site/Header";
import { Footer } from "@/components/site/Footer";
import { HomeUpload } from "@/components/site/HomeUpload";
import { TOOLS } from "@/lib/tools-registry";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [{ title: "Lazy PDF — Private, fast PDF tools" }, { name: "description", content: "Edit, convert, organize, compress, sign, and protect PDFs in your browser with a polished private toolkit." }, { property: "og:title", content: "Lazy PDF — Private, fast PDF tools" }, { property: "og:description", content: "A complete PDF workspace that keeps documents on your device." }] }),
  component: LandingPage,
});

const popularSlugs = ["merge", "compress", "edit", "pdf-to-word", "jpg-to-pdf", "sign"];
const faqs = [
  { q: "Do my PDFs leave my device?", a: "Normal processing runs in your browser. Document bytes are not uploaded or stored. Shared-link cloud import is an explicit exception: the selected public file is streamed once to your browser and never retained." },
  { q: "Which formats are supported?", a: "Lazy PDF works with PDF, JPG, PNG, DOCX, XLSX, PPTX, HTML, EPUB, ZIP exports, and plain text depending on the selected tool." },
  { q: "Is there a file size limit?", a: "Local uploads are validated up to 200 MB. Actual processing capacity depends on device memory and document complexity. Cloud shared-link imports are capped at 50 MB." },
  { q: "Do I need an account?", a: "No. Every PDF tool works without an account. Signing in only adds a synced history of filenames, sizes, and favorite operations—never document contents." },
  { q: "How much does it cost?", a: "The complete browser toolkit is free. The account workspace is also free and optional." },
];

function LandingPage() {
  const popular = popularSlugs.map((slug) => TOOLS.find((tool) => tool.slug === slug)).filter(Boolean) as typeof TOOLS;
  return <div className="min-h-screen"><Header />
    <main>
      <section className="relative overflow-hidden px-4 pb-16 pt-16 sm:px-6 sm:pt-24"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_75%_20%,color-mix(in_oklab,var(--signal)_18%,transparent),transparent_30%)]" /><div className="relative mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1fr_0.88fr]">
        <motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .55 }}><div className="inline-flex items-center gap-2 rounded-full border border-border bg-card/70 px-3 py-1.5 text-xs font-medium text-muted-foreground"><Sparkles className="h-3.5 w-3.5 text-signal" />45 focused tools. One private workspace.</div><h1 className="mt-6 max-w-4xl font-display text-5xl leading-[.98] sm:text-6xl lg:text-7xl">PDF work,<br /><span className="ink-gradient-text">without the friction.</span></h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-muted-foreground">Organize, edit, convert, sign, secure, and export documents at browser speed. No queues. No mysterious uploads. No clutter.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#upload" className="inline-flex items-center rounded-full bg-primary px-6 py-3 text-sm font-medium text-primary-foreground shadow-lg shadow-ink/10">Choose a file <ArrowRight className="ml-2 h-4 w-4" /></a><Link to="/tools" className="inline-flex items-center rounded-full border border-border bg-card px-6 py-3 text-sm font-medium hover:border-signal">Explore all tools</Link></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-sm text-muted-foreground">{["No document storage", "Works on mobile", "Valid downloadable files"].map((item) => <span key={item} className="flex items-center gap-2"><Check className="h-4 w-4 text-signal" />{item}</span>)}</div></motion.div>
        <motion.div id="upload" initial={{ opacity: 0, scale: .97 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: .12, duration: .55 }}><HomeUpload /></motion.div>
      </div></section>

      <section className="border-y border-border bg-card/45 px-4 py-6 sm:px-6"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-center gap-x-8 gap-y-3 text-xs font-semibold uppercase tracking-[.18em] text-muted-foreground"><span>Supported formats</span>{["PDF", "DOCX", "XLSX", "PPTX", "JPG", "PNG", "HTML", "EPUB"].map((format) => <span key={format} className="text-foreground">{format}</span>)}</div></section>

      <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6"><div className="flex items-end justify-between gap-4"><div><div className="text-xs font-semibold uppercase tracking-[.2em] text-signal">Popular tools</div><h2 className="mt-2 font-display text-4xl sm:text-5xl">Start with what you need.</h2></div><Link to="/tools" className="hidden items-center text-sm font-medium sm:inline-flex">View all <ArrowRight className="ml-2 h-4 w-4" /></Link></div><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{popular.map((tool) => <Link key={tool.slug} to="/tools/$slug" params={{ slug: tool.slug }} className="group rounded-[1.5rem] border border-border bg-card p-6 shadow-sm transition hover:-translate-y-1 hover:border-signal hover:shadow-xl hover:shadow-ink/5"><div className={`grid h-12 w-12 place-items-center rounded-2xl bg-gradient-to-br ${tool.accentClass}`}><tool.icon className="h-5 w-5 text-ink" /></div><h3 className="mt-5 font-display text-xl">{tool.name}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{tool.tagline}</p><span className="mt-5 inline-flex items-center text-sm font-medium text-signal">Open tool <ArrowRight className="ml-1 h-4 w-4 transition-transform group-hover:translate-x-1" /></span></Link>)}</div></section>

      <section id="features" className="bg-primary px-4 py-20 text-primary-foreground sm:px-6"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><div className="text-xs font-semibold uppercase tracking-[.2em] text-signal">Why Lazy PDF</div><h2 className="mt-3 font-display text-4xl sm:text-5xl">Fast enough to disappear into your workflow.</h2></div><div className="mt-12 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{[{ icon: ShieldCheck, title: "Private by design", text: "PDF processing happens locally. Account history stores metadata only." }, { icon: Gauge, title: "Immediate output", text: "No upload queue or server round-trip for standard tools." }, { icon: WandSparkles, title: "Real manipulation", text: "Every listed tool creates an actual document or data export." }, { icon: MonitorSmartphone, title: "Any modern device", text: "Responsive controls work across desktop and mobile browsers." }].map((item) => <div key={item.title}><item.icon className="h-6 w-6 text-signal" /><h3 className="mt-5 text-lg font-semibold">{item.title}</h3><p className="mt-2 text-sm leading-relaxed text-primary-foreground/65">{item.text}</p></div>)}</div></div></section>

      <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6"><div className="grid gap-6 lg:grid-cols-3">{[{ icon: Layers3, title: "Organize", text: "Merge, split, reorder, rotate, extract, and delete pages with precise controls." }, { icon: Zap, title: "Convert", text: "Move between PDF, Office, image, HTML, EPUB, text, and archive formats." }, { icon: LockKeyhole, title: "Finish securely", text: "Sign, redact, protect, unlock, flatten, watermark, and repair documents." }].map((item, index) => <div key={item.title} className="rounded-[1.75rem] border border-border bg-card p-7"><span className="font-display text-5xl text-signal/30">0{index + 1}</span><item.icon className="mt-6 h-6 w-6 text-signal" /><h2 className="mt-4 font-display text-2xl">{item.title}</h2><p className="mt-2 leading-relaxed text-muted-foreground">{item.text}</p></div>)}</div></section>

      <section id="pricing" className="px-4 py-20 sm:px-6"><div className="mx-auto max-w-5xl rounded-[2.5rem] border border-border bg-card p-8 shadow-2xl shadow-ink/5 sm:p-12"><div className="grid gap-10 lg:grid-cols-[1fr_.8fr]"><div><div className="text-xs font-semibold uppercase tracking-[.2em] text-signal">Simple pricing</div><h2 className="mt-3 font-display text-4xl sm:text-5xl">The complete toolkit is free.</h2><p className="mt-4 max-w-xl text-muted-foreground">Process as many files as your device can handle. Create an optional account for synced activity and favorites.</p></div><div className="rounded-3xl bg-secondary p-6"><div className="text-sm font-medium">Private Free</div><div className="mt-2 font-display text-5xl">$0</div><div className="text-sm text-muted-foreground">No card. No trial clock.</div><div className="mt-6 grid gap-3 text-sm">{["All PDF and conversion tools", "Optional synced dashboard", "Local document processing", "No watermarks added"].map((item) => <span key={item} className="flex gap-2"><Check className="h-4 w-4 text-signal" />{item}</span>)}</div></div></div></div></section>

      <section id="faq" className="mx-auto max-w-3xl px-4 py-20 sm:px-6"><div className="text-xs font-semibold uppercase tracking-[.2em] text-signal">FAQ</div><h2 className="mt-2 font-display text-4xl sm:text-5xl">Clear answers, before you upload.</h2><Accordion type="single" collapsible className="mt-8">{faqs.map((item, index) => <AccordionItem key={item.q} value={`faq-${index}`}><AccordionTrigger className="text-left">{item.q}</AccordionTrigger><AccordionContent className="leading-relaxed text-muted-foreground">{item.a}</AccordionContent></AccordionItem>)}</Accordion></section>
    </main><Footer /></div>;
}
